# Cross.toml
[build]
channel = "nightly-2024-08-01"

# For x86_64-unknown-linux-gnu target
[target.x86_64-unknown-linux-gnu]
pre-build = [
    "export DEBIAN_FRONTEND=noninteractive",
    "export TZ=Etc/UTC",
    "dpkg --add-architecture $CROSS_DEB_ARCH",
    "apt update -q && apt upgrade -yq && apt install --assume-yes --no-install-recommends libclang-14-dev clang-14 cmake build-essential pkg-config libssl-dev:$CROSS_DEB_ARCH libsasl2-dev llvm-dev gnutls-bin"
]

[target.aarch64-unknown-linux-gnu]
pre-build = [
    "export DEBIAN_FRONTEND=noninteractive",
    "export TZ=Etc/UTC",
    "export CROSS_DEB_ARCH=arm64",
    "dpkg --add-architecture $CROSS_DEB_ARCH",
    "apt update -q && apt upgrade -yq && apt install --assume-yes --no-install-recommends libclang-14-dev clang-14 cmake build-essential pkg-config libssl-dev:$CROSS_DEB_ARCH libsasl2-dev llvm-dev gnutls-bin"
]
