# Cross.toml
[build]
channel = "nightly-2024-08-01"

# For x86_64-unknown-linux-gnu target
[target.x86_64-unknown-linux-gnu]
image = "ubuntu:22.04"
pre-build = [
    "export DEBIAN_FRONTEND=noninteractive",
    "export TZ=Etc/UTC",
    "dpkg --add-architecture $CROSS_DEB_ARCH",
    "apt update -q && apt upgrade -yq && apt install --assume-yes --no-install-recommends libclang-dev clang cmake build-essential pkg-config gcc g++ libssl-dev:$CROSS_DEB_ARCH libc6-dev libsasl2-dev llvm-dev gnutls-bin"
]

# For aarch64-unknown-linux-gnu target
[target.aarch64-unknown-linux-gnu]
image = "ubuntu:22.04"
pre-build = [
    "apt-get update",
    "apt-get install -y --no-install-recommends build-essential gcc-aarch64-linux-gnu g++-aarch64-linux-gnu libc6-dev-arm64-cross cmake pkg-config"
]